/** @type {import('tailwindcss').Config} */

// ── Theming ────────────────────────────────────────────────────────────────
// Every colour utility resolves through a CSS variable instead of a fixed hex,
// so toggling `.dark` on <html> retints the entire app (see src/theme.css,
// generated by scripts/generate-theme.cjs). Class names never change — a
// component written as `bg-white text-gray-500 border-navy-100` just works in
// both themes.
//
// The three variable sets exist because a colour means different things per
// property: `bg-white` is a surface (goes dark), `text-white` is a label on a
// solid button (stays white), `border-gray-200` is a hairline (goes dark).
const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
const FAMILIES = [
  'gray', 'slate', 'zinc', 'stone', 'red', 'orange', 'amber', 'yellow', 'lime',
  'green', 'emerald', 'teal', 'cyan', 'sky', 'indigo', 'violet', 'purple',
  'fuchsia', 'pink', 'rose', 'blue', 'navy',
];
const BRAND_KEYS = ['blue', 'blueDark', 'blueLight', 'accent', 'red', 'white', 'gray', 'grayDark', 'surface', 'muted'];

// `prefix` is bg | tx | bd. Falls back to the light hex baked into theme.css.
const scale = (prefix) =>
  Object.fromEntries(
    FAMILIES.map((family) => [
      family,
      Object.fromEntries(SHADES.map((shade) => [shade, `rgb(var(--${prefix}-${family}-${shade}) / <alpha-value>)`])),
    ]),
  );
const brand = (prefix, fallbackPrefix) =>
  Object.fromEntries(
    BRAND_KEYS.map((key) => [key, `rgb(var(--${prefix}-brand-${key}, var(--${fallbackPrefix}-brand-${key})) / <alpha-value>)`]),
  );

const surfaces = () => ({
  ...scale('bg'),
  ...{ white: 'rgb(var(--bg-white) / <alpha-value>)', black: 'rgb(var(--bg-black) / <alpha-value>)' },
  brand: brand('bg', 'bg'),
});
const inks = () => ({
  ...scale('tx'),
  brand: brand('tx', 'bg'),
});
const lines = () => ({
  ...scale('bd'),
  brand: brand('bd', 'bg'),
});

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        navy: {
          50: '#EEF2FA',
          100: '#D6DFF1',
          200: '#AEBFE2',
          300: '#7E96CB',
          400: '#506FAF',
          500: '#2F4F95',
          600: '#1E3A8A',
          700: '#16306E',
          800: '#102452',
          900: '#0A1838',
        },
        blue: {
          50: '#EFF5FF',
          100: '#DBE7FE',
          200: '#BAD0FC',
          300: '#8FB1F8',
          400: '#5C8AF2',
          500: '#3A6BE0',
          600: '#1E50C7',
          700: '#1E3A8A',
          800: '#172E6C',
          900: '#0F1F4D',
        },
        brand: {
          blue: '#1E3A8A',
          blueDark: '#102452',
          blueLight: '#3A6BE0',
          accent: '#DBE7FE',
          red: '#E63329',
          white: '#FFFFFF',
          gray: '#EEF1F6',
          grayDark: '#D6DBE5',
          surface: '#FFFFFF',
          muted: '#6B7385',
        },
      },
      // Theme-aware colour sections. `colors` above stays literal — it feeds
      // anything not listed here (shadow tints, `theme()` lookups in classes).
      backgroundColor: surfaces(),
      gradientColorStops: surfaces(),
      textColor: inks(),
      placeholderColor: inks(),
      textDecorationColor: inks(),
      fill: inks(),
      stroke: inks(),
      borderColor: { DEFAULT: 'rgb(var(--bd-gray-200) / <alpha-value>)', ...lines() },
      divideColor: lines(),
      ringColor: { DEFAULT: 'rgb(var(--bd-blue-500) / <alpha-value>)', ...lines() },
      // Focus rings punch a gap in the surface behind them — keep it matching.
      ringOffsetColor: {
        DEFAULT: 'rgb(var(--bg-white))',
        white: 'rgb(var(--bg-white))',
        ...scale('bg'),
      },
      fontFamily: {
        sans: ['"DM Sans"', 'system-ui', 'sans-serif'],
        display: ['"Sora"', '"DM Sans"', 'system-ui', 'sans-serif'],
      },
      // Shadow tint follows the theme: navy-tinted on light, plain black and
      // noticeably deeper on dark (a soft navy glow reads as nothing there).
      boxShadow: {
        card: `0 1px 2px rgb(var(--shadow-rgb) / calc(0.05 * var(--shadow-strength))),
               0 4px 16px -2px rgb(var(--shadow-rgb) / calc(0.07 * var(--shadow-strength)))`,
        cardHover: `0 4px 12px rgb(var(--shadow-rgb) / calc(0.08 * var(--shadow-strength))),
                    0 16px 32px -8px rgb(var(--shadow-rgb) / calc(0.14 * var(--shadow-strength)))`,
        pop: `0 8px 24px -6px rgb(var(--shadow-rgb) / calc(0.18 * var(--shadow-strength))),
              0 2px 6px rgb(var(--shadow-rgb) / calc(0.08 * var(--shadow-strength)))`,
        btn: `0 1px 2px rgb(var(--shadow-rgb) / calc(0.18 * var(--shadow-strength))),
              inset 0 1px 0 rgba(255, 255, 255, 0.12)`,
      },
      keyframes: {
        marquee: {
          '0%':   { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-400px 0' },
          '100%': { backgroundPosition: '400px 0' },
        },
      },
      animation: {
        marquee: 'marquee 40s linear infinite',
        shimmer: 'shimmer 1.6s linear infinite',
      },
    },
  },
  plugins: [],
};
