const express = require('express');
const { z } = require('zod');
const prisma = require('../config/db');
const { authenticate } = require('../middleware/auth');
const { authorize } = require('../middleware/rbac');
const { generateSequentialNumber, paginate, applyDateFilter, isUniqueViolation, deptForRole, validateWorkOrderLink } = require('../utils/helpers');

const router = express.Router();

// Roles whose MIV visibility is scoped to "own only" on the read endpoints.
// Includes the non-unit owner departments (QC, LAB, SAFETY, DESIGNS,
// METROLOGY, NDT) so they can issue the stock reserved to their department.
// PLANNING is intentionally excluded here — it keeps org-wide read visibility
// (sees every MIV), so it never gets scoped down to its own.
const REQUESTER_ROLES = ['MANAGER', 'LAB', 'QC', 'RND', 'SAFETY', 'DESIGNS', 'METROLOGY', 'NDT'];
// Roles allowed to create/collect/cancel MIVs. PLANNING may raise/issue its own
// (the per-handler managerId checks keep it to its own) while still monitoring
// the whole org via the unscoped listing — so it is added here but NOT to
// REQUESTER_ROLES above.
const MANAGE_ROLES = [...REQUESTER_ROLES, 'PLANNING'];
// Unit-bound roles must belong to a unit; everyone else (QC, LAB, SAFETY,
// DESIGNS, PLANNING …) may file without one — their MIV draws from their
// department's reserved bucket and the unassigned pool.
const UNIT_BOUND_ROLES = ['MANAGER', 'RND'];

// Per-MIV-line reverse map: which gate pass(es) carried this offsite line out.
// Attached to RequestItem.gatePassLinks on the read endpoints so the MIV view can
// show GP no. ↔ MIV no. mapping, dispatch + arrival dates, and vehicle.
const OFFSITE_GP_LINK_INCLUDE = {
  gatePassItem: {
    select: {
      id: true,
      gatePass: {
        select: {
          id: true, passNumber: true, status: true, dispatchedAt: true,
          reachedDate: true, vehicleNo: true, driverName: true, siteName: true,
          destinationUnitId: true,
        },
      },
    },
  },
};

const createRequestSchema = z.object({
  notes: z.string().optional(),
  remarks: z.string().optional(),
  // Required header-level link to the Work Order this MIV is issued against.
  workOrderId: z.string().uuid({ message: 'Work Order is required' }),
  // referenceNo is auto-generated by the server (mirrors the MIV request number)
  items: z.array(z.object({
    productId: z.string().uuid(),
    quantity: z.number().positive(),
    purpose: z.string().optional(),
  })).min(1),
});

// Same shape as create — used when the owner edits a still-PENDING MIV before
// the store accepts it. Items are fully replaced (no stock has moved yet).
const editRequestSchema = createRequestSchema;

// ──── Shared MIV issue helpers (used by both /approve and /issue-available) ────
// Per-item availability = (a) the requester's own bucket — a unit bucket
// (ProductUnitStock) for unit requesters, or a department bucket
// (ProductDeptStock) for non-unit owner roles (QC, Designs, …) — plus (b) the
// unassigned pool = currentStock minus every unit AND department reservation.
// Stock reserved to a *different* unit or department is off-limits.
async function computeAvailability(client, request, requesterDept) {
  const availabilityByItem = {};
  for (const ri of request.items) {
    if (ri.quantity <= 0) {
      availabilityByItem[ri.id] = { ownUnitQty: 0, ownDeptQty: 0, unassignedQty: 0, available: 0 };
      continue;
    }
    const [ownUnitBucket, ownDeptBucket, allUnitBuckets, allDeptBuckets] = await Promise.all([
      request.unitId
        ? client.productUnitStock.findUnique({
            where: { productId_unitId: { productId: ri.productId, unitId: request.unitId } },
          })
        : Promise.resolve(null),
      requesterDept
        ? client.productDeptStock.findUnique({
            where: { productId_dept: { productId: ri.productId, dept: requesterDept } },
          })
        : Promise.resolve(null),
      client.productUnitStock.findMany({ where: { productId: ri.productId }, select: { quantity: true } }),
      client.productDeptStock.findMany({ where: { productId: ri.productId }, select: { quantity: true } }),
    ]);
    const ownUnitQty = ownUnitBucket?.quantity || 0;
    const ownDeptQty = ownDeptBucket?.quantity || 0;
    const assignedTotal =
      allUnitBuckets.reduce((s, b) => s + b.quantity, 0) +
      allDeptBuckets.reduce((s, b) => s + b.quantity, 0);
    const unassignedQty = Math.max(0, (ri.product?.currentStock || 0) - assignedTotal);
    availabilityByItem[ri.id] = {
      ownUnitQty, ownDeptQty, unassignedQty,
      available: ownUnitQty + ownDeptQty + unassignedQty,
    };
  }
  return availabilityByItem;
}

// Issue `take` units of one request item inside a transaction: FIFO batch
// draw-down, currentStock + own-bucket decrement, and an OUT stockMovement.
// Does NOT touch the RequestItem row — callers update qtyIssued/collectedQty
// themselves (set on first issue, increment on top-up). Returns FIFO slices.
async function issueItemQty(tx, { request, item, take, requesterDept, availability, performedBy, note }) {
  if (!(take > 0)) return [];

  const batches = await tx.productBatch.findMany({
    where: { productId: item.productId, remaining: { gt: 0 } },
    orderBy: { receivedDate: 'asc' },
  });
  let toFulfill = take;
  const slices = [];
  for (const batch of batches) {
    if (toFulfill <= 0) break;
    const slice = Math.min(batch.remaining, toFulfill);
    await tx.productBatch.update({
      where: { id: batch.id },
      data: { remaining: batch.remaining - slice },
    });
    slices.push({ batchId: batch.id, batchNo: batch.batchNo, quantity: slice });
    toFulfill -= slice;
  }
  const batchNoString = slices.map(s => s.batchNo).filter(Boolean).join(', ') || null;

  await tx.product.update({
    where: { id: item.productId },
    data: { currentStock: { decrement: take } },
  });

  // Draw from the requester's own bucket first (unit OR department ledger),
  // then from the unassigned pool (no ledger row — only currentStock moves).
  const av = availability || {};
  if (request.unitId) {
    const fromOwn = Math.min(av.ownUnitQty || 0, take);
    if (fromOwn > 0) {
      await tx.productUnitStock.update({
        where: { productId_unitId: { productId: item.productId, unitId: request.unitId } },
        data: { quantity: { decrement: fromOwn } },
      });
    }
  } else if (requesterDept) {
    const fromOwn = Math.min(av.ownDeptQty || 0, take);
    if (fromOwn > 0) {
      await tx.productDeptStock.update({
        where: { productId_dept: { productId: item.productId, dept: requesterDept } },
        data: { quantity: { decrement: fromOwn } },
      });
    }
  }

  await tx.stockMovement.create({
    data: {
      productId: item.productId,
      type: 'OUT',
      quantity: take,
      referenceType: 'ProductRequest',
      referenceId: request.id,
      batchNumber: batchNoString,
      notes: `${note} [FIFO: ${slices.map(s => `${s.batchNo || 'NO-BATCH'}×${s.quantity}`).join(', ') || 'none'}]`,
      performedBy,
      unitId: request.unitId,
    },
  });

  return slices;
}

// GET /api/requests — list requests based on role
router.get('/', authenticate, async (req, res) => {
  try {
    const { status, page, limit, fromDate, toDate } = req.query;
    const { skip, take } = paginate(page, limit);

    const where = {};
    applyDateFilter(where, { fromDate, toDate });

    // Role-based filtering — requester roles see only their own
    if (REQUESTER_ROLES.includes(req.user.role)) {
      where.managerId = req.user.id;
    }
    // STORE_MANAGER and ADMIN see all
    if (status) where.status = status;

    const [requests, total] = await Promise.all([
      prisma.productRequest.findMany({
        where,
        include: {
          manager: { select: { id: true, name: true, username: true, role: true } },
          unit: { select: { id: true, name: true, code: true, isOffsite: true } },
          workOrder: { select: { id: true, workOrderNumber: true, supplyOrderNo: true } },
          items: {
            include: {
              product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } },
              gatePassLinks: { include: OFFSITE_GP_LINK_INCLUDE },
            },
          },
        },
        orderBy: { createdAt: 'desc' },
        skip,
        take,
      }),
      prisma.productRequest.count({ where }),
    ]);

    res.json({ requests, total, page: Math.ceil(skip / take) + 1, totalPages: Math.ceil(total / take) });
  } catch (error) {
    console.error('Get requests error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// GET /api/requests/pending-count
router.get('/pending-count', authenticate, async (req, res) => {
  try {
    const count = await prisma.productRequest.count({ where: { status: 'PENDING' } });
    res.json({ count });
  } catch (error) {
    console.error('Pending count error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// GET /api/requests/:id
router.get('/:id', authenticate, async (req, res) => {
  try {
    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: {
        manager: { select: { id: true, name: true, username: true, role: true, unit: { select: { name: true, code: true } } } },
        unit: { select: { id: true, name: true, code: true, isOffsite: true } },
        workOrder: { select: { id: true, workOrderNumber: true, supplyOrderNo: true } },
        items: {
          include: {
            product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true, category: true } },
            gatePassLinks: { include: OFFSITE_GP_LINK_INCLUDE },
          },
        },
      },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });

    // Requester roles can only view their own requests
    if (REQUESTER_ROLES.includes(req.user.role) && request.managerId !== req.user.id) {
      return res.status(403).json({ error: 'Access denied' });
    }

    res.json(request);
  } catch (error) {
    console.error('Get request error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// POST /api/requests — Requester creates a product request
router.post('/', authenticate, authorize(...MANAGE_ROLES), async (req, res) => {
  try {
    const data = createRequestSchema.parse(req.body);

    if (!req.user.unitId && UNIT_BOUND_ROLES.includes(req.user.role)) {
      return res.status(400).json({ error: 'You must be assigned to a unit to create requests' });
    }

    // Optional Work Order link. null = "No work order". Unit requesters may only
    // link a WO assigned to their own unit.
    const woLink = await validateWorkOrderLink(prisma, data.workOrderId, req.user.unitId || null);
    if (!woLink.ok) return res.status(400).json({ error: woLink.error });

    // Offsite units route to ADMIN for approval (with qty edit) instead of the
    // store auto-issue path; everything else is unchanged.
    const offsiteUnit = req.user.unitId
      ? await prisma.unit.findUnique({ where: { id: req.user.unitId }, select: { isOffsite: true } })
      : null;
    const isOffsite = !!offsiteUnit?.isOffsite;

    const requestNumber = await generateSequentialNumber(prisma, 'MIV');

    const request = await prisma.productRequest.create({
      data: {
        requestNumber,
        managerId: req.user.id,
        unitId: req.user.unitId || null,
        workOrderId: woLink.workOrderId,
        notes: data.notes || null,
        remarks: data.remarks || null,
        // referenceNo auto-mirrors the MIV request number — no manual entry.
        referenceNo: requestNumber,
        items: {
          create: data.items.map(item => ({
            productId: item.productId,
            quantity: item.quantity,
            purpose: item.purpose || null,
          })),
        },
      },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        workOrder: { select: { id: true, workOrderNumber: true, supplyOrderNo: true } },
        items: {
          include: { product: { select: { id: true, name: true, sku: true, unit: true } } },
        },
      },
    });

    // Audit log
    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'CREATE',
        entity: 'ProductRequest',
        entityId: request.id,
        details: {
          requestNumber,
          unit: req.user.unit?.code,
          itemCount: data.items.length,
        },
        ipAddress: req.ip,
      },
    });

    // Notify the next approver: ADMIN for offsite MIVs, store managers otherwise.
    await prisma.notification.create({
      data: {
        type: 'NEW_REQUEST',
        title: `New ${isOffsite ? 'Offsite ' : ''}MIV: ${requestNumber}`,
        message: isOffsite
          ? `${req.user.name}${req.user.unit ? ` (${req.user.unit.name})` : ''} raised offsite MIV ${requestNumber} with ${data.items.length} item(s). Awaiting your approval.`
          : `${req.user.name}${req.user.unit ? ` (${req.user.unit.name})` : ` (${req.user.role})`} has submitted a new product request with ${data.items.length} item(s).`,
        targetRole: isOffsite ? 'ADMIN' : 'STORE_MANAGER',
        sentById: req.user.id,
      },
    });

    res.status(201).json(request);
  } catch (error) {
    if (error instanceof z.ZodError) {
      return res.status(400).json({ error: 'Invalid input', details: error.errors });
    }
    console.error('Create request error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// PUT /api/requests/:id/edit — Owner edits a still-PENDING MIV before the store
// accepts it. Replaces notes/remarks and the full item list. Only the creator
// may edit, and only while PENDING (nothing has been issued, so it's safe).
router.put('/:id/edit', authenticate, authorize(...MANAGE_ROLES), async (req, res) => {
  try {
    const data = editRequestSchema.parse(req.body);

    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.managerId !== req.user.id) {
      return res.status(403).json({ error: 'You can only edit your own requests' });
    }
    if (request.status !== 'PENDING') {
      return res.status(400).json({ error: 'Only pending requests can be edited' });
    }

    // Re-validate the optional Work Order link against the MIV's own unit.
    const woLink = await validateWorkOrderLink(prisma, data.workOrderId, request.unitId);
    if (!woLink.ok) return res.status(400).json({ error: woLink.error });

    // Full replace of items inside a transaction — no stock has moved on a
    // PENDING MIV, so deleting and recreating the rows is safe.
    await prisma.$transaction(async (tx) => {
      await tx.requestItem.deleteMany({ where: { requestId: request.id } });
      await tx.productRequest.update({
        where: { id: request.id },
        data: {
          notes: data.notes || null,
          remarks: data.remarks || null,
          workOrderId: woLink.workOrderId,
          items: {
            create: data.items.map(item => ({
              productId: item.productId,
              quantity: item.quantity,
              purpose: item.purpose || null,
            })),
          },
        },
      });
    });

    const updated = await prisma.productRequest.findUnique({
      where: { id: request.id },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        items: {
          include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } },
        },
      },
    });

    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'UPDATE',
        entity: 'ProductRequest',
        entityId: request.id,
        details: {
          requestNumber: request.requestNumber,
          action: 'EDITED_BEFORE_ACCEPTANCE',
          itemCount: data.items.length,
        },
        ipAddress: req.ip,
      },
    });

    // Let the store know the pending MIV changed before they act on it.
    await prisma.notification.create({
      data: {
        type: 'NEW_REQUEST',
        title: `MIV ${request.requestNumber} updated`,
        message: `${req.user.name} edited the pending MIV ${request.requestNumber} (now ${data.items.length} item(s)) before acceptance.`,
        targetRole: 'STORE_MANAGER',
        sentById: req.user.id,
      },
    });

    res.json(updated);
  } catch (error) {
    if (error instanceof z.ZodError) {
      return res.status(400).json({ error: 'Invalid input', details: error.errors });
    }
    console.error('Edit request error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// PUT /api/requests/:id/approve — Store Manager accepts the MIV.
// Body: {} — store fills nothing. Everything is auto-derived:
//   • approvedQty = qtyIssued = original requested qty
//   • issueNo auto-generated, issueDate = now()
//   • materialBatchNo = FIFO-picked product batch numbers
//   • stock decremented immediately (global + per-unit), batch remaining drawn down
//   • status flips straight to COLLECTED — no separate "collect" step
router.put('/:id/approve', authenticate, authorize('STORE_MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: {
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } } },
        manager: { select: { id: true, name: true, role: true } },
        unit: { select: { id: true, name: true, code: true, isOffsite: true } },
      },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.unit?.isOffsite) {
      return res.status(400).json({ error: 'Offsite MIVs are approved by an admin and dispatched on a gate pass — this store-issue path does not apply.' });
    }
    if (request.status !== 'PENDING') {
      return res.status(400).json({ error: 'Only pending requests can be approved' });
    }

    // Partial issue: no longer all-or-nothing. Issue whatever is available to
    // the requester right now (own reserved bucket + unassigned pool), per item.
    // Items with insufficient stock get whatever's there; the remainder waits
    // and the MIV is left PARTIAL so the store can top it up once stock arrives.
    const requesterDept = request.unitId ? null : deptForRole(request.manager?.role);
    const availabilityByItem = await computeAvailability(prisma, request, requesterDept);

    // Decide how much to issue per item this round = min(requested, available).
    const takeByItem = {};
    let totalIssuedQty = 0;
    for (const ri of request.items) {
      const av = availabilityByItem[ri.id] || { available: 0 };
      const take = Math.max(0, Math.min(ri.quantity, av.available));
      takeByItem[ri.id] = take;
      totalIssuedQty += take;
    }

    // An Issue No is only minted when something actually leaves stock.
    const issueNo = totalIssuedQty > 0 ? await generateSequentialNumber(prisma, 'ISS') : null;
    const now = new Date();
    const fifoSlicesByItem = {};

    await prisma.$transaction(async (tx) => {
      for (const item of request.items) {
        const take = takeByItem[item.id] || 0;
        const slices = await issueItemQty(tx, {
          request,
          item,
          take,
          requesterDept,
          availability: availabilityByItem[item.id],
          performedBy: req.user.id,
          note: `MIV ${request.requestNumber} accepted by ${req.user.name} for ${request.unit?.name || request.manager?.name || 'requester'}`,
        });
        fifoSlicesByItem[item.id] = slices;
        const batchNoString = slices.map(s => s.batchNo).filter(Boolean).join(', ') || null;

        await tx.requestItem.update({
          where: { id: item.id },
          data: {
            approvedQty: item.quantity, // full accepted qty; qtyIssued tracks what's gone out
            qtyIssued: take,
            collectedQty: take,
            materialBatchNo: batchNoString,
          },
        });
      }

      // COLLECTED only when every item is fully issued; otherwise PARTIAL (waiting).
      const fullyIssued = request.items.every(ri => (takeByItem[ri.id] || 0) >= ri.quantity - 0.001);
      await tx.productRequest.update({
        where: { id: req.params.id },
        data: {
          status: fullyIssued ? 'COLLECTED' : 'PARTIAL',
          clearedById: req.user.id,
          clearedAt: now,
          ...(fullyIssued ? { collectedAt: now } : {}),
          ...(issueNo ? { issueNo, issueDate: now } : {}),
        },
      });
    });

    const fullyIssuedCount = request.items.filter(i => (takeByItem[i.id] || 0) >= i.quantity - 0.001).length;
    const allDone = fullyIssuedCount === request.items.length;

    const updated = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } } },
      },
    });

    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'APPROVE',
        entity: 'ProductRequest',
        entityId: request.id,
        details: {
          requestNumber: request.requestNumber,
          issueNo,
          action: allDone ? 'ACCEPTED_AND_ISSUED' : 'ACCEPTED_AND_PARTIALLY_ISSUED',
          items: request.items.map(i => ({
            product: i.product?.name,
            qty: i.quantity,
            issued: takeByItem[i.id] || 0,
            pending: Math.max(0, i.quantity - (takeByItem[i.id] || 0)),
            fifoBatches: fifoSlicesByItem[i.id] || [],
          })),
        },
        ipAddress: req.ip,
      },
    });

    await prisma.notification.create({
      data: {
        type: 'REQUEST_APPROVED',
        title: `MIV ${request.requestNumber} accepted`,
        message: allDone
          ? `Your MIV ${request.requestNumber} has been accepted by ${req.user.name}. Issue No: ${issueNo}. Materials issued from stock.`
          : `Your MIV ${request.requestNumber} has been accepted by ${req.user.name} (partial). ${fullyIssuedCount}/${request.items.length} item(s) issued${issueNo ? ` — Issue No: ${issueNo}` : ''}; the remaining items are waiting on stock and will be issued when available.`,
        targetUserId: request.managerId,
        sentById: req.user.id,
      },
    });

    // Low-stock notifications after issue.
    for (const item of request.items) {
      const product = await prisma.product.findUnique({ where: { id: item.productId } });
      if (product && product.minStockLevel > 0 && product.currentStock <= product.minStockLevel) {
        const existing = await prisma.notification.findFirst({
          where: { productId: product.id, isRead: false, type: 'LOW_STOCK' },
        });
        if (!existing) {
          await prisma.notification.create({
            data: {
              type: 'LOW_STOCK',
              title: `LOW STOCK: ${product.name}`,
              message: `${product.name} (${product.sku}) stock is at ${product.currentStock} ${product.unit}. Minimum level: ${product.minStockLevel}.`,
              productId: product.id,
              targetRole: 'STORE_MANAGER',
            },
          });
        }
      }
    }

    res.json(updated);
  } catch (error) {
    console.error('Approve request error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
});

// PUT /api/requests/:id/issue-available — Store Manager tops up a PARTIAL MIV.
// Issues whatever is now available against each item's still-pending qty
// (pending = approvedQty − qtyIssued). Advances the MIV to COLLECTED once every
// item is fully issued, otherwise it stays PARTIAL for the next top-up.
router.put('/:id/issue-available', authenticate, authorize('STORE_MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: {
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } } },
        manager: { select: { id: true, name: true, role: true } },
        unit: { select: { id: true, name: true, code: true, isOffsite: true } },
      },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.unit?.isOffsite) {
      return res.status(400).json({ error: 'Offsite MIVs are dispatched on gate passes — this store-issue path does not apply.' });
    }
    if (request.status !== 'PARTIAL') {
      return res.status(400).json({ error: 'Only partially-issued MIVs can be topped up' });
    }

    const requesterDept = request.unitId ? null : deptForRole(request.manager?.role);
    const availabilityByItem = await computeAvailability(prisma, request, requesterDept);

    // This round's take per item = min(stillPending, availableNow).
    const takeByItem = {};
    let totalIssuedQty = 0;
    for (const ri of request.items) {
      const approved = ri.approvedQty ?? ri.quantity;
      const pending = Math.max(0, approved - (ri.qtyIssued || 0));
      const av = availabilityByItem[ri.id] || { available: 0 };
      const take = Math.max(0, Math.min(pending, av.available));
      takeByItem[ri.id] = take;
      totalIssuedQty += take;
    }

    if (totalIssuedQty <= 0) {
      return res.status(400).json({ error: 'No additional stock is available to issue for the pending items yet.' });
    }

    // Reuse the existing Issue No if one was minted at accept time; otherwise mint now.
    const issueNo = request.issueNo || await generateSequentialNumber(prisma, 'ISS');
    const now = new Date();
    const fifoSlicesByItem = {};

    await prisma.$transaction(async (tx) => {
      for (const item of request.items) {
        const take = takeByItem[item.id] || 0;
        if (take <= 0) { fifoSlicesByItem[item.id] = []; continue; }
        const slices = await issueItemQty(tx, {
          request,
          item,
          take,
          requesterDept,
          availability: availabilityByItem[item.id],
          performedBy: req.user.id,
          note: `MIV ${request.requestNumber} top-up issue by ${req.user.name} for ${request.unit?.name || request.manager?.name || 'requester'}`,
        });
        fifoSlicesByItem[item.id] = slices;
        const newBatchNo = slices.map(s => s.batchNo).filter(Boolean).join(', ');
        const mergedBatchNo = [item.materialBatchNo, newBatchNo].filter(Boolean).join(', ') || null;

        await tx.requestItem.update({
          where: { id: item.id },
          data: {
            qtyIssued: { increment: take },
            collectedQty: { increment: take },
            materialBatchNo: mergedBatchNo,
          },
        });
      }

      const fullyIssued = request.items.every(ri => {
        const approved = ri.approvedQty ?? ri.quantity;
        return ((ri.qtyIssued || 0) + (takeByItem[ri.id] || 0)) >= approved - 0.001;
      });

      await tx.productRequest.update({
        where: { id: req.params.id },
        data: {
          status: fullyIssued ? 'COLLECTED' : 'PARTIAL',
          issueNo,
          issueDate: request.issueDate || now,
          ...(fullyIssued ? { collectedAt: now } : {}),
        },
      });
    });

    const fullyIssuedCount = request.items.filter(ri => {
      const approved = ri.approvedQty ?? ri.quantity;
      return ((ri.qtyIssued || 0) + (takeByItem[ri.id] || 0)) >= approved - 0.001;
    }).length;
    const allDone = fullyIssuedCount === request.items.length;

    const updated = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } } },
      },
    });

    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'ISSUE_AVAILABLE',
        entity: 'ProductRequest',
        entityId: request.id,
        details: {
          requestNumber: request.requestNumber,
          issueNo,
          completed: allDone,
          items: request.items.map(i => ({
            product: i.product?.name,
            issuedThisRound: takeByItem[i.id] || 0,
            fifoBatches: fifoSlicesByItem[i.id] || [],
          })),
        },
        ipAddress: req.ip,
      },
    });

    await prisma.notification.create({
      data: {
        type: 'REQUEST_APPROVED',
        title: allDone ? `MIV ${request.requestNumber} fully issued` : `MIV ${request.requestNumber} partly issued`,
        message: allDone
          ? `Your MIV ${request.requestNumber} is now fully issued by ${req.user.name}. Issue No: ${issueNo}.`
          : `${req.user.name} issued more stock against your MIV ${request.requestNumber}. Some items are still waiting on stock.`,
        targetUserId: request.managerId,
        sentById: req.user.id,
      },
    });

    // Low-stock notifications after issue.
    for (const item of request.items) {
      const product = await prisma.product.findUnique({ where: { id: item.productId } });
      if (product && product.minStockLevel > 0 && product.currentStock <= product.minStockLevel) {
        const existing = await prisma.notification.findFirst({
          where: { productId: product.id, isRead: false, type: 'LOW_STOCK' },
        });
        if (!existing) {
          await prisma.notification.create({
            data: {
              type: 'LOW_STOCK',
              title: `LOW STOCK: ${product.name}`,
              message: `${product.name} (${product.sku}) stock is at ${product.currentStock} ${product.unit}. Minimum level: ${product.minStockLevel}.`,
              productId: product.id,
              targetRole: 'STORE_MANAGER',
            },
          });
        }
      }
    }

    res.json(updated);
  } catch (error) {
    console.error('Issue-available request error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
});

// PUT /api/requests/:id/reject — Store Manager rejects
router.put('/:id/reject', authenticate, authorize('STORE_MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const { clearanceNotes } = req.body;

    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: { manager: { select: { name: true } } },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.status !== 'PENDING') {
      return res.status(400).json({ error: 'Only pending requests can be rejected' });
    }

    const updated = await prisma.productRequest.update({
      where: { id: req.params.id },
      data: {
        status: 'REJECTED',
        clearanceNotes: clearanceNotes || 'Request rejected',
        clearedById: req.user.id,
        clearedAt: new Date(),
      },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true } } } },
      },
    });

    // Audit log
    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'REJECT',
        entity: 'ProductRequest',
        entityId: request.id,
        details: { requestNumber: request.requestNumber, action: 'REJECTED', reason: clearanceNotes },
        ipAddress: req.ip,
      },
    });

    // Notify the creator (look up their role)
    await prisma.notification.create({
      data: {
        type: 'REQUEST_REJECTED',
        title: `Request ${request.requestNumber} Rejected`,
        message: `Your product request ${request.requestNumber} has been rejected. Reason: ${clearanceNotes || 'No reason provided'}`,
        targetUserId: request.managerId,
        sentById: req.user.id,
      },
    });

    res.json(updated);
  } catch (error) {
    console.error('Reject request error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// PUT /api/requests/:id/collect — Requester collects items (full or partial)
// Body: { items?: [{ id, collectedQty }] }  — defaults to each item's remaining approvedQty
router.put('/:id/collect', authenticate, authorize(...MANAGE_ROLES), async (req, res) => {
  try {
    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: { items: { include: { product: true } }, unit: true },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.unit?.isOffsite) {
      return res.status(400).json({ error: 'Offsite MIVs are received by acknowledging the gate pass, not collected from the store.' });
    }
    if (request.managerId !== req.user.id) {
      return res.status(403).json({ error: 'You can only collect your own requests' });
    }
    if (request.status !== 'APPROVED' && request.status !== 'PARTIAL') {
      return res.status(400).json({ error: 'Only approved or partially collected requests can be collected' });
    }

    // The collector is the requester (checked above), so their role gives the
    // owning department for non-unit MIVs.
    const requesterDept = request.unitId ? null : deptForRole(req.user.role);

    // Build collect-plan: how much each item takes this round (delta)
    const bodyItems = Array.isArray(req.body?.items) ? req.body.items : null;
    const plan = [];
    for (const item of request.items) {
      const approved = item.approvedQty ?? item.quantity;
      const alreadyTaken = item.collectedQty || 0;
      const maxRemaining = Math.max(0, approved - alreadyTaken);

      let take;
      if (bodyItems) {
        const override = bodyItems.find((b) => b.id === item.id);
        if (!override) { take = 0; continue; } // omitted = collect 0 this round
        take = Number(override.collectedQty);
        if (!Number.isFinite(take) || take < 0) {
          return res.status(400).json({ error: `Invalid collectedQty for item ${item.id}` });
        }
      } else {
        take = maxRemaining; // default: collect everything remaining
      }

      if (take > maxRemaining) {
        return res.status(400).json({
          error: `collectedQty ${take} exceeds remaining ${maxRemaining} for ${item.product.name}`,
        });
      }
      if (take > 0) plan.push({ item, take });
    }

    if (plan.length === 0) {
      return res.status(400).json({ error: 'Nothing to collect — provide at least one item with qty > 0' });
    }

    // FIFO: deduct from oldest batches first
    const fifoIssuedByItem = {};
    await prisma.$transaction(async (tx) => {
      for (const { item, take } of plan) {
        const batches = await tx.productBatch.findMany({
          where: { productId: item.productId, remaining: { gt: 0 } },
          orderBy: { receivedDate: 'asc' },
        });

        let toFulfill = take;
        const issuedSlices = [];
        for (const batch of batches) {
          if (toFulfill <= 0) break;
          const slice = Math.min(batch.remaining, toFulfill);
          await tx.productBatch.update({
            where: { id: batch.id },
            data: { remaining: batch.remaining - slice },
          });
          issuedSlices.push({
            batchId: batch.id,
            batchNo: batch.batchNo,
            receivedDate: batch.receivedDate,
            quantity: slice,
          });
          toFulfill -= slice;
        }
        fifoIssuedByItem[item.id] = issuedSlices;

        await tx.product.update({
          where: { id: item.productId },
          data: { currentStock: { decrement: take } },
        });

        // Decrement the requester's own reserved bucket. Unit requesters draw from
        // their unit bucket; non-unit owner departments (QC, Designs, …) from their
        // department bucket. Unit-less non-owner MIVs draw the unassigned pool —
        // only Product.currentStock is decremented (done above).
        if (request.unitId) {
          const pus = await tx.productUnitStock.findUnique({
            where: { productId_unitId: { productId: item.productId, unitId: request.unitId } },
          });
          if (!pus || pus.quantity < take - 0.001) {
            throw new Error(`Unit ${request.unit?.code || request.unitId} stock for ${item.product?.name || 'product'} is insufficient — please raise an inventory transfer first.`);
          }
          await tx.productUnitStock.update({
            where: { productId_unitId: { productId: item.productId, unitId: request.unitId } },
            data: { quantity: { decrement: take } },
          });
        } else if (requesterDept) {
          const pds = await tx.productDeptStock.findUnique({
            where: { productId_dept: { productId: item.productId, dept: requesterDept } },
          });
          if (!pds || pds.quantity < take - 0.001) {
            throw new Error(`${requesterDept} department stock for ${item.product?.name || 'product'} is insufficient — please raise an inventory transfer first.`);
          }
          await tx.productDeptStock.update({
            where: { productId_dept: { productId: item.productId, dept: requesterDept } },
            data: { quantity: { decrement: take } },
          });
        }

        await tx.requestItem.update({
          where: { id: item.id },
          data: { collectedQty: { increment: take } },
        });

        const batchNote = issuedSlices.length > 0
          ? ` [FIFO: ${issuedSlices.map(s => `${s.batchNo || 'NO-BATCH'}×${s.quantity}`).join(', ')}]`
          : '';

        await tx.stockMovement.create({
          data: {
            productId: item.productId,
            type: 'OUT',
            quantity: take,
            referenceType: 'ProductRequest',
            referenceId: request.id,
            batchNumber: issuedSlices.map(s => s.batchNo).filter(Boolean).join(', ') || null,
            notes: `Collected by ${req.user.name} for ${request.unit?.name || request.manager?.name || 'requester'} (${request.requestNumber})${batchNote}`,
            performedBy: req.user.id,
            unitId: request.unitId,
          },
        });
      }

      // Determine final status: COLLECTED if every item fully taken, else PARTIAL
      const refreshed = await tx.requestItem.findMany({ where: { requestId: request.id } });
      const fullyDone = refreshed.every((ri) => (ri.collectedQty || 0) >= (ri.approvedQty ?? ri.quantity));

      await tx.productRequest.update({
        where: { id: req.params.id },
        data: fullyDone
          ? { status: 'COLLECTED', collectedAt: new Date() }
          : { status: 'PARTIAL' },
      });
    });

    // Audit log
    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'COLLECT',
        entity: 'ProductRequest',
        entityId: request.id,
        details: {
          requestNumber: request.requestNumber,
          unit: request.unit?.code || null,
          items: plan.map(({ item, take }) => ({
            product: item.product.name,
            qtyTaken: take,
            fifoBatches: fifoIssuedByItem[item.id] || [],
          })),
        },
        ipAddress: req.ip,
      },
    });

    // Check for low stock and auto-notify
    for (const item of request.items) {
      const product = await prisma.product.findUnique({ where: { id: item.productId } });
      if (product && product.minStockLevel > 0 && product.currentStock <= product.minStockLevel) {
        const existing = await prisma.notification.findFirst({
          where: { productId: product.id, isRead: false, type: 'LOW_STOCK' },
        });
        if (!existing) {
          await prisma.notification.create({
            data: {
              type: 'LOW_STOCK',
              title: `LOW STOCK: ${product.name}`,
              message: `${product.name} (${product.sku}) stock is at ${product.currentStock} ${product.unit}. Minimum level: ${product.minStockLevel}.`,
              productId: product.id,
              targetRole: 'STORE_MANAGER',
            },
          });
        }
      }
    }

    const updated = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } } },
      },
    });

    res.json(updated);
  } catch (error) {
    console.error('Collect request error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// PUT /api/requests/:id/kill-remaining — Requester closes a PARTIAL request without collecting more
router.put('/:id/kill-remaining', authenticate, authorize(...MANAGE_ROLES), async (req, res) => {
  try {
    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: { items: { include: { product: true } }, unit: true },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.unit?.isOffsite) {
      return res.status(400).json({ error: 'Offsite MIVs close automatically once every gate pass is acknowledged.' });
    }
    if (request.managerId !== req.user.id) {
      return res.status(403).json({ error: 'You can only modify your own requests' });
    }
    if (request.status !== 'PARTIAL') {
      return res.status(400).json({ error: 'Only partially collected requests can be closed this way' });
    }

    const updated = await prisma.productRequest.update({
      where: { id: req.params.id },
      data: { status: 'COLLECTED', collectedAt: new Date() },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } } },
      },
    });

    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'KILL_REMAINING',
        entity: 'ProductRequest',
        entityId: request.id,
        details: {
          requestNumber: request.requestNumber,
          items: request.items.map((i) => ({
            product: i.product.name,
            approvedQty: i.approvedQty ?? i.quantity,
            collectedQty: i.collectedQty || 0,
            killedQty: Math.max(0, (i.approvedQty ?? i.quantity) - (i.collectedQty || 0)),
          })),
        },
        ipAddress: req.ip,
      },
    });

    res.json(updated);
  } catch (error) {
    console.error('Kill remaining error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// PUT /api/requests/:id/cancel — Requester cancels own pending request
router.put('/:id/cancel', authenticate, authorize(...MANAGE_ROLES), async (req, res) => {
  try {
    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.managerId !== req.user.id) {
      return res.status(403).json({ error: 'You can only cancel your own requests' });
    }
    if (request.status !== 'PENDING') {
      return res.status(400).json({ error: 'Only pending requests can be cancelled' });
    }

    const updated = await prisma.productRequest.update({
      where: { id: req.params.id },
      data: { status: 'CANCELLED' },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true } } } },
      },
    });

    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'CANCEL',
        entity: 'ProductRequest',
        entityId: request.id,
        details: { requestNumber: request.requestNumber, action: 'CANCELLED' },
        ipAddress: req.ip,
      },
    });

    res.json(updated);
  } catch (error) {
    console.error('Cancel request error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// ════════════════════════════════════════════════════════════════════════════
// OFFSITE MIV DISPATCH  (units flagged Unit.isOffsite — ANSP, CPDC, Adibatla, …)
// ────────────────────────────────────────────────────────────────────────────
// Flow:  site MANAGER raises MIV → ADMIN approves (may edit qty) → central store
// builds NON_RETURNABLE gate passes for selected lines/qty (one GP = one site,
// may bundle several of that site's MIVs) → store/logistics attaches a vehicle &
// dispatches → the site's MANAGER acks receipt, closing the GP. A MIV closes
// (COLLECTED) only once every approved qty is dispatched AND every GP it rode on
// has been acknowledged.
// ════════════════════════════════════════════════════════════════════════════

// FIFO draw for an offsite dispatch: pull `take` units from the oldest batches and
// decrement Product.currentStock. Returns the picked batch-number string; the
// caller logs the OUT stockMovement (GatePass reference) and bumps dispatchedQty.
async function dispatchFifo(tx, productId, take) {
  const batches = await tx.productBatch.findMany({
    where: { productId, remaining: { gt: 0 } },
    orderBy: { receivedDate: 'asc' },
  });
  let toFulfill = take;
  const slices = [];
  for (const batch of batches) {
    if (toFulfill <= 0) break;
    const slice = Math.min(batch.remaining, toFulfill);
    await tx.productBatch.update({ where: { id: batch.id }, data: { remaining: batch.remaining - slice } });
    slices.push({ batchNo: batch.batchNo, quantity: slice });
    toFulfill -= slice;
  }
  return { batchNo: slices.map(s => s.batchNo).filter(Boolean).join(', ') || null, slices };
}

// Notify the active MANAGERs of a unit by user id (scoped — avoids paging every
// manager org-wide). `extra` merges into each notification.
async function notifyUnitManagers(unitId, extra) {
  const managers = await prisma.user.findMany({
    where: { role: 'MANAGER', unitId, isActive: true },
    select: { id: true },
  });
  await Promise.all(managers.map((m) => prisma.notification.create({
    data: { ...extra, targetUserId: m.id },
  })));
}

// Recompute closure for one offsite MIV inside a txn. COLLECTED once every line is
// fully dispatched AND every gate pass it rode on is CLOSED (acked). Otherwise it
// stays PARTIAL (in-progress). Returns the resulting status.
async function recomputeOffsiteMivStatus(tx, requestId) {
  const request = await tx.productRequest.findUnique({
    where: { id: requestId },
    include: {
      items: { include: { gatePassLinks: { include: { gatePassItem: { select: { gatePass: { select: { status: true } } } } } } } },
    },
  });
  if (!request) return null;
  if (['REJECTED', 'CANCELLED'].includes(request.status)) return request.status;

  const fullyDispatched = request.items.every((ri) => {
    const approved = ri.approvedQty ?? ri.quantity;
    return (ri.dispatchedQty || 0) >= approved - 0.001;
  });
  const allGpStatuses = request.items.flatMap((ri) => ri.gatePassLinks.map((l) => l.gatePassItem.gatePass.status));
  const hasAnyGp = allGpStatuses.length > 0;
  const allGpClosed = allGpStatuses.every((s) => s === 'CLOSED');

  const done = fullyDispatched && hasAnyGp && allGpClosed;
  const next = done ? 'COLLECTED' : 'PARTIAL';
  await tx.productRequest.update({
    where: { id: requestId },
    data: { status: next, ...(done ? { collectedAt: new Date() } : {}) },
  });
  return next;
}

// PUT /api/requests/:id/admin-approve — ADMIN approves an offsite MIV and may edit
// per-line quantities. Body: { items?: [{ id, approvedQty }], notes? }. Lines not
// listed keep their requested qty. Moves the MIV to APPROVED (awaiting dispatch).
router.put('/:id/admin-approve', authenticate, authorize('ADMIN'), async (req, res) => {
  try {
    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: {
        items: { include: { product: { select: { id: true, name: true } } } },
        manager: { select: { id: true, name: true, role: true } },
        unit: { select: { id: true, name: true, code: true, isOffsite: true } },
      },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (!request.unit?.isOffsite) return res.status(400).json({ error: 'Admin approval applies to offsite MIVs only' });
    if (request.status !== 'PENDING') return res.status(400).json({ error: 'Only pending MIVs can be approved' });

    const overrides = Array.isArray(req.body?.items) ? req.body.items : [];
    // Resolve approved qty per line: explicit override (>= 0) or the requested qty.
    const approvedByItem = {};
    for (const ri of request.items) {
      const ov = overrides.find((o) => o.id === ri.id);
      let qty = ri.quantity;
      if (ov && ov.approvedQty !== undefined && ov.approvedQty !== null) {
        qty = Number(ov.approvedQty);
        if (!Number.isFinite(qty) || qty < 0) {
          return res.status(400).json({ error: `Invalid approvedQty for item ${ri.id}` });
        }
      }
      approvedByItem[ri.id] = qty;
    }

    await prisma.$transaction(async (tx) => {
      for (const ri of request.items) {
        await tx.requestItem.update({ where: { id: ri.id }, data: { approvedQty: approvedByItem[ri.id] } });
      }
      await tx.productRequest.update({
        where: { id: request.id },
        data: {
          status: 'APPROVED',
          clearedById: req.user.id,
          clearedAt: new Date(),
          ...(req.body?.notes ? { clearanceNotes: String(req.body.notes) } : {}),
        },
      });
    });

    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'APPROVE',
        entity: 'ProductRequest',
        entityId: request.id,
        details: {
          requestNumber: request.requestNumber,
          action: 'OFFSITE_ADMIN_APPROVED',
          items: request.items.map((i) => ({ product: i.product?.name, requested: i.quantity, approved: approvedByItem[i.id] })),
        },
        ipAddress: req.ip,
      },
    });

    // Stores can now dispatch; tell the requester it cleared.
    await prisma.notification.create({
      data: {
        type: 'NEW_REQUEST',
        title: `Offsite MIV ${request.requestNumber} approved`,
        message: `${req.user.name} approved offsite MIV ${request.requestNumber} for ${request.unit?.name}. Ready for dispatch.`,
        targetRole: 'STORE_MANAGER',
        sentById: req.user.id,
      },
    });
    await prisma.notification.create({
      data: {
        type: 'REQUEST_APPROVED',
        title: `Offsite MIV ${request.requestNumber} approved`,
        message: `Your offsite MIV ${request.requestNumber} was approved by ${req.user.name}. Stores will dispatch the material.`,
        targetUserId: request.managerId,
        sentById: req.user.id,
      },
    });

    const updated = await prisma.productRequest.findUnique({
      where: { id: request.id },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true, isOffsite: true } },
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true } } } },
      },
    });
    res.json(updated);
  } catch (error) {
    console.error('Offsite admin-approve error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
});

// GET /api/requests/offsite/queue — APPROVED/PARTIAL offsite MIVs that still have
// qty left to dispatch. Powers the store's gate-pass builder. STORE_MANAGER/ADMIN.
router.get('/offsite/queue', authenticate, authorize('STORE_MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const requests = await prisma.productRequest.findMany({
      where: { unit: { isOffsite: true }, status: { in: ['APPROVED', 'PARTIAL'] } },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        workOrder: { select: { id: true, workOrderNumber: true } },
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } } },
      },
      orderBy: { createdAt: 'asc' },
    });
    // Keep only MIVs with at least one line still owing qty.
    const open = requests.filter((r) => r.items.some((i) => ((i.approvedQty ?? i.quantity) - (i.dispatchedQty || 0)) > 0.001));
    res.json(open);
  } catch (error) {
    console.error('Offsite queue error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// GET /api/requests/offsite/gatepasses — dispatched-lot tracker. Each GP with its
// items, MIV-no mapping, vehicle and ack status. MANAGERs see only their own
// unit's; STORE_MANAGER/ADMIN/LOGISTICS see all.
router.get('/offsite/gatepasses', authenticate, async (req, res) => {
  try {
    const where = { kind: 'OUTSIDE', destinationUnit: { isOffsite: true } };
    // Scope unit-bound requesters (incl. site managers) to their own unit.
    if (!['ADMIN', 'STORE_MANAGER', 'LOGISTICS'].includes(req.user.role)) {
      if (!req.user.unitId) return res.json([]);
      where.destinationUnitId = req.user.unitId;
    }
    const gatePasses = await prisma.gatePass.findMany({
      where,
      include: {
        destinationUnit: { select: { id: true, name: true, code: true } },
        assignedVehicle: { select: { id: true, regNumber: true } },
        createdBy: { select: { id: true, name: true } },
        items: {
          include: {
            mivLinks: {
              include: { requestItem: { select: { id: true, request: { select: { id: true, requestNumber: true } } } } },
            },
          },
        },
      },
      orderBy: { createdAt: 'desc' },
    });
    res.json(gatePasses);
  } catch (error) {
    console.error('Offsite gatepasses error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// POST /api/requests/offsite/gatepass — central store builds a NON_RETURNABLE gate
// pass for selected offsite-MIV lines (one site only; may bundle several MIVs).
// Body: { unitId, passNumber?, items: [{ requestItemId, quantity }] }. FIFO-draws
// stock now; the GP then awaits a vehicle. STORE_MANAGER/ADMIN.
router.post('/offsite/gatepass', authenticate, authorize('STORE_MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const { unitId, passNumber: rawPassNumber } = req.body || {};
    const lines = Array.isArray(req.body?.items) ? req.body.items : [];
    if (!unitId) return res.status(400).json({ error: 'unitId is required' });
    if (lines.length === 0) return res.status(400).json({ error: 'Select at least one item to dispatch' });

    const unit = await prisma.unit.findUnique({ where: { id: unitId }, select: { id: true, name: true, isOffsite: true } });
    if (!unit) return res.status(404).json({ error: 'Unit not found' });
    if (!unit.isOffsite) return res.status(400).json({ error: 'Gate-pass dispatch applies to offsite units only' });

    // Load + validate every selected MIV line.
    const resolved = [];
    for (const ln of lines) {
      const qty = Number(ln.quantity);
      if (!ln.requestItemId || !Number.isFinite(qty) || qty <= 0) {
        return res.status(400).json({ error: 'Each item needs a requestItemId and a positive quantity' });
      }
      const ri = await prisma.requestItem.findUnique({
        where: { id: ln.requestItemId },
        include: {
          product: { select: { id: true, name: true, unit: true, currentStock: true } },
          request: { select: { id: true, requestNumber: true, unitId: true, status: true, unit: { select: { isOffsite: true } } } },
        },
      });
      if (!ri) return res.status(404).json({ error: `MIV line ${ln.requestItemId} not found` });
      if (!ri.request.unit?.isOffsite || ri.request.unitId !== unitId) {
        return res.status(400).json({ error: 'All selected lines must belong to the same offsite unit' });
      }
      if (!['APPROVED', 'PARTIAL'].includes(ri.request.status)) {
        return res.status(400).json({ error: `MIV ${ri.request.requestNumber} is not approved for dispatch` });
      }
      const remaining = (ri.approvedQty ?? ri.quantity) - (ri.dispatchedQty || 0);
      if (qty > remaining + 0.001) {
        return res.status(400).json({ error: `${ri.product.name}: qty ${qty} exceeds remaining ${remaining} on MIV ${ri.request.requestNumber}` });
      }
      resolved.push({ ri, qty });
    }

    // Stock check (aggregate per product across the selected lines).
    const neededByProduct = {};
    for (const { ri, qty } of resolved) neededByProduct[ri.productId] = (neededByProduct[ri.productId] || 0) + qty;
    for (const [productId, need] of Object.entries(neededByProduct)) {
      const p = resolved.find((r) => r.ri.productId === productId).ri.product;
      if ((p.currentStock || 0) < need - 0.001) {
        return res.status(400).json({ error: `Insufficient stock for ${p.name}: need ${need}, have ${p.currentStock || 0}` });
      }
    }

    const passNumber = (rawPassNumber || '').trim() || await generateSequentialNumber(prisma, 'GP');
    const affectedRequestIds = [...new Set(resolved.map((r) => r.ri.request.id))];

    const created = await prisma.$transaction(async (tx) => {
      const gp = await tx.gatePass.create({
        data: {
          passNumber,
          direction: 'OUTWARD',
          kind: 'OUTSIDE',
          passType: 'NON_RETURNABLE',
          status: 'PENDING_LOGISTICS',
          destinationUnitId: unit.id,
          siteName: unit.name,
          createdById: req.user.id,
        },
      });

      for (const { ri, qty } of resolved) {
        const { batchNo } = await dispatchFifo(tx, ri.productId, qty);
        await tx.product.update({ where: { id: ri.productId }, data: { currentStock: { decrement: qty } } });

        const gpItem = await tx.gatePassItem.create({
          data: {
            gatePassId: gp.id,
            description: ri.product.name,
            quantity: qty,
            unit: ri.product.unit || 'pcs',
            itemPassType: 'NON_RETURNABLE',
            dispatchedTo: unit.name,
            gatePassDetails: `MIV ${ri.request.requestNumber}${batchNo ? ` · Batch ${batchNo}` : ''}`,
          },
        });
        await tx.gatePassMivLink.create({ data: { gatePassItemId: gpItem.id, requestItemId: ri.id, quantity: qty } });
        await tx.requestItem.update({ where: { id: ri.id }, data: { dispatchedQty: { increment: qty } } });

        await tx.stockMovement.create({
          data: {
            productId: ri.productId,
            type: 'OUT',
            quantity: qty,
            referenceType: 'GatePass',
            referenceId: gp.id,
            batchNumber: batchNo,
            notes: `Offsite dispatch GP ${passNumber} → ${unit.name} (MIV ${ri.request.requestNumber})`,
            performedBy: req.user.id,
            unitId: unit.id,
          },
        });
      }

      // Touched MIVs go to PARTIAL (in-progress) until fully dispatched + acked.
      for (const rid of affectedRequestIds) await recomputeOffsiteMivStatus(tx, rid);
      return gp;
    });

    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'CREATE',
        entity: 'GatePass',
        entityId: created.id,
        details: {
          passNumber, unit: unit.name, kind: 'OUTSIDE', passType: 'NON_RETURNABLE',
          mivs: affectedRequestIds.length, lines: resolved.length,
        },
        ipAddress: req.ip,
      },
    });

    const gatePass = await prisma.gatePass.findUnique({
      where: { id: created.id },
      include: {
        destinationUnit: { select: { id: true, name: true, code: true } },
        items: { include: { mivLinks: { include: { requestItem: { select: { request: { select: { requestNumber: true } } } } } } } },
      },
    });
    res.status(201).json(gatePass);
  } catch (error) {
    console.error('Offsite gatepass build error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
});

// POST /api/requests/offsite/gatepass/:gpId/dispatch — attach a vehicle and send
// the consignment. Body: { vehicleId?, driverId?, privateVehicle?{regNumber,
// driverName, driverPhone} }. STORE_MANAGER, LOGISTICS or ADMIN.
router.post('/offsite/gatepass/:gpId/dispatch', authenticate, authorize('STORE_MANAGER', 'LOGISTICS', 'ADMIN'), async (req, res) => {
  try {
    const { vehicleId, driverId, privateVehicle } = req.body || {};
    const gp = await prisma.gatePass.findUnique({
      where: { id: req.params.gpId },
      include: { destinationUnit: { select: { id: true, name: true, isOffsite: true } } },
    });
    if (!gp) return res.status(404).json({ error: 'Gate pass not found' });
    if (gp.kind !== 'OUTSIDE' || !gp.destinationUnit?.isOffsite) {
      return res.status(400).json({ error: 'Not an offsite gate pass' });
    }
    if (gp.status !== 'PENDING_LOGISTICS') return res.status(400).json({ error: 'Gate pass is not awaiting dispatch' });
    if (!vehicleId && !privateVehicle) return res.status(400).json({ error: 'A vehicle (registered or private) is required to dispatch' });

    const data = { status: 'IN_TRANSIT', dispatchedAt: new Date(), logisticsById: req.user.id, logisticsAt: new Date() };

    if (vehicleId) {
      const vehicle = await prisma.vehicle.findUnique({ where: { id: vehicleId } });
      if (!vehicle) return res.status(400).json({ error: 'Vehicle not found' });
      if (vehicle.status !== 'ACTIVE') return res.status(400).json({ error: 'Vehicle is not ACTIVE' });
      let driver = null;
      if (driverId) {
        driver = await prisma.driver.findUnique({ where: { id: driverId } });
        if (!driver) return res.status(400).json({ error: 'Driver not found' });
      }
      Object.assign(data, {
        assignedVehicleId: vehicle.id,
        assignedDriverId: driver?.id || null,
        privateVehicle: false,
        vehicleNo: vehicle.regNumber,
        driverName: driver?.name || vehicle.driverName,
        driverPhone: driver?.phone || vehicle.driverPhone || null,
      });
    } else {
      const regNumber = (privateVehicle.regNumber || '').trim();
      const pvDriverName = (privateVehicle.driverName || '').trim();
      if (!regNumber) return res.status(400).json({ error: 'Private vehicle number is required' });
      if (!pvDriverName) return res.status(400).json({ error: 'Driver name is required for a private vehicle' });
      Object.assign(data, {
        assignedVehicleId: null,
        assignedDriverId: null,
        privateVehicle: true,
        vehicleNo: regNumber.toUpperCase(),
        driverName: pvDriverName,
        driverPhone: (privateVehicle.driverPhone || '').trim() || null,
      });
    }

    const updated = await prisma.gatePass.update({ where: { id: gp.id }, data });

    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'LOGISTICS_DISPATCH',
        entity: 'GatePass',
        entityId: gp.id,
        details: { passNumber: gp.passNumber, unit: gp.destinationUnit?.name, vehicleNo: updated.vehicleNo },
        ipAddress: req.ip,
      },
    });

    await notifyUnitManagers(gp.destinationUnitId, {
      type: 'GATE_PASS_STAGE',
      title: `Materials dispatched: ${gp.passNumber}`,
      message: `${req.user.name} dispatched gate pass ${gp.passNumber} to ${gp.destinationUnit?.name} on vehicle ${updated.vehicleNo || ''}. Acknowledge receipt when it arrives.`,
      sentById: req.user.id,
    });

    res.json(updated);
  } catch (error) {
    console.error('Offsite dispatch error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
});

// PUT /api/requests/offsite/gatepass/:gpId/ack — the destination site's MANAGER
// acknowledges receipt. Closes the GP (non-returnable) and re-evaluates closure of
// every MIV it carried. MANAGER (own unit only) or ADMIN.
router.put('/offsite/gatepass/:gpId/ack', authenticate, authorize('MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const gp = await prisma.gatePass.findUnique({
      where: { id: req.params.gpId },
      include: {
        destinationUnit: { select: { id: true, name: true, isOffsite: true } },
        items: { include: { mivLinks: { include: { requestItem: { select: { requestId: true } } } } } },
      },
    });
    if (!gp) return res.status(404).json({ error: 'Gate pass not found' });
    if (gp.kind !== 'OUTSIDE' || !gp.destinationUnit?.isOffsite) return res.status(400).json({ error: 'Not an offsite gate pass' });
    if (gp.status !== 'IN_TRANSIT') return res.status(400).json({ error: 'Gate pass is not in transit' });
    if (req.user.role === 'MANAGER' && req.user.unitId !== gp.destinationUnitId) {
      return res.status(403).json({ error: 'You can only acknowledge gate passes sent to your unit' });
    }

    const now = new Date();
    const requestIds = [...new Set(gp.items.flatMap((it) => it.mivLinks.map((l) => l.requestItem.requestId)))];

    await prisma.$transaction(async (tx) => {
      await tx.gatePass.update({
        where: { id: gp.id },
        data: {
          status: 'CLOSED',
          reachedDate: now,
          siteOfficeAckById: req.user.id,
          siteOfficeAckAt: now,
          collectedById: req.user.id,
          collectedAt: now,
          approvedById: req.user.id,
          approvedAt: now,
        },
      });
      for (const rid of requestIds) await recomputeOffsiteMivStatus(tx, rid);
    });

    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'COLLECT',
        entity: 'GatePass',
        entityId: gp.id,
        details: { passNumber: gp.passNumber, action: 'OFFSITE_RECEIPT_ACK', unit: gp.destinationUnit?.name },
        ipAddress: req.ip,
      },
    });

    await prisma.notification.create({
      data: {
        type: 'GATE_PASS_APPROVED',
        title: `Receipt confirmed: ${gp.passNumber}`,
        message: `${req.user.name} confirmed ${gp.destinationUnit?.name} received gate pass ${gp.passNumber}.`,
        targetRole: 'STORE_MANAGER',
        sentById: req.user.id,
      },
    });

    const updated = await prisma.gatePass.findUnique({
      where: { id: gp.id },
      include: {
        destinationUnit: { select: { id: true, name: true, code: true } },
        items: { include: { mivLinks: { include: { requestItem: { select: { request: { select: { requestNumber: true } } } } } } } },
      },
    });
    res.json(updated);
  } catch (error) {
    console.error('Offsite ack error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
});

module.exports = router;
