const express = require('express');
const { z } = require('zod');
const prisma = require('../config/db');
const { authenticate } = require('../middleware/auth');
const { authorize } = require('../middleware/rbac');
const { generateSequentialNumber, paginate, applyDateFilter, isUniqueViolation, deptForRole } = require('../utils/helpers');

const router = express.Router();

// Roles that can create/manage their own MIV requests (same privileges as MANAGER).
// Includes the non-unit owner departments (QC, LAB, SAFETY, DESIGNS,
// METROLOGY, NDT) so they can issue the stock reserved to their department.
// PLANNING is intentionally excluded — it is a read-only monitor (sees every
// MIV across the org) and never raises or issues its own.
const REQUESTER_ROLES = ['MANAGER', 'LAB', 'QC', 'RND', 'SAFETY', 'DESIGNS', 'METROLOGY', 'NDT'];
// Unit-bound roles must belong to a unit; everyone else (QC, LAB, SAFETY,
// DESIGNS …) may file without one — their MIV draws from their department's
// reserved bucket and the unassigned pool.
const UNIT_BOUND_ROLES = ['MANAGER', 'RND'];

const createRequestSchema = z.object({
  notes: z.string().optional(),
  remarks: z.string().optional(),
  // referenceNo is auto-generated by the server (mirrors the MIV request number)
  items: z.array(z.object({
    productId: z.string().uuid(),
    quantity: z.number().positive(),
    purpose: z.string().optional(),
  })).min(1),
});

// ──── Shared MIV issue helpers (used by both /approve and /issue-available) ────
// Per-item availability = (a) the requester's own bucket — a unit bucket
// (ProductUnitStock) for unit requesters, or a department bucket
// (ProductDeptStock) for non-unit owner roles (QC, Designs, …) — plus (b) the
// unassigned pool = currentStock minus every unit AND department reservation.
// Stock reserved to a *different* unit or department is off-limits.
async function computeAvailability(client, request, requesterDept) {
  const availabilityByItem = {};
  for (const ri of request.items) {
    if (ri.quantity <= 0) {
      availabilityByItem[ri.id] = { ownUnitQty: 0, ownDeptQty: 0, unassignedQty: 0, available: 0 };
      continue;
    }
    const [ownUnitBucket, ownDeptBucket, allUnitBuckets, allDeptBuckets] = await Promise.all([
      request.unitId
        ? client.productUnitStock.findUnique({
            where: { productId_unitId: { productId: ri.productId, unitId: request.unitId } },
          })
        : Promise.resolve(null),
      requesterDept
        ? client.productDeptStock.findUnique({
            where: { productId_dept: { productId: ri.productId, dept: requesterDept } },
          })
        : Promise.resolve(null),
      client.productUnitStock.findMany({ where: { productId: ri.productId }, select: { quantity: true } }),
      client.productDeptStock.findMany({ where: { productId: ri.productId }, select: { quantity: true } }),
    ]);
    const ownUnitQty = ownUnitBucket?.quantity || 0;
    const ownDeptQty = ownDeptBucket?.quantity || 0;
    const assignedTotal =
      allUnitBuckets.reduce((s, b) => s + b.quantity, 0) +
      allDeptBuckets.reduce((s, b) => s + b.quantity, 0);
    const unassignedQty = Math.max(0, (ri.product?.currentStock || 0) - assignedTotal);
    availabilityByItem[ri.id] = {
      ownUnitQty, ownDeptQty, unassignedQty,
      available: ownUnitQty + ownDeptQty + unassignedQty,
    };
  }
  return availabilityByItem;
}

// Issue `take` units of one request item inside a transaction: FIFO batch
// draw-down, currentStock + own-bucket decrement, and an OUT stockMovement.
// Does NOT touch the RequestItem row — callers update qtyIssued/collectedQty
// themselves (set on first issue, increment on top-up). Returns FIFO slices.
async function issueItemQty(tx, { request, item, take, requesterDept, availability, performedBy, note }) {
  if (!(take > 0)) return [];

  const batches = await tx.productBatch.findMany({
    where: { productId: item.productId, remaining: { gt: 0 } },
    orderBy: { receivedDate: 'asc' },
  });
  let toFulfill = take;
  const slices = [];
  for (const batch of batches) {
    if (toFulfill <= 0) break;
    const slice = Math.min(batch.remaining, toFulfill);
    await tx.productBatch.update({
      where: { id: batch.id },
      data: { remaining: batch.remaining - slice },
    });
    slices.push({ batchId: batch.id, batchNo: batch.batchNo, quantity: slice });
    toFulfill -= slice;
  }
  const batchNoString = slices.map(s => s.batchNo).filter(Boolean).join(', ') || null;

  await tx.product.update({
    where: { id: item.productId },
    data: { currentStock: { decrement: take } },
  });

  // Draw from the requester's own bucket first (unit OR department ledger),
  // then from the unassigned pool (no ledger row — only currentStock moves).
  const av = availability || {};
  if (request.unitId) {
    const fromOwn = Math.min(av.ownUnitQty || 0, take);
    if (fromOwn > 0) {
      await tx.productUnitStock.update({
        where: { productId_unitId: { productId: item.productId, unitId: request.unitId } },
        data: { quantity: { decrement: fromOwn } },
      });
    }
  } else if (requesterDept) {
    const fromOwn = Math.min(av.ownDeptQty || 0, take);
    if (fromOwn > 0) {
      await tx.productDeptStock.update({
        where: { productId_dept: { productId: item.productId, dept: requesterDept } },
        data: { quantity: { decrement: fromOwn } },
      });
    }
  }

  await tx.stockMovement.create({
    data: {
      productId: item.productId,
      type: 'OUT',
      quantity: take,
      referenceType: 'ProductRequest',
      referenceId: request.id,
      batchNumber: batchNoString,
      notes: `${note} [FIFO: ${slices.map(s => `${s.batchNo || 'NO-BATCH'}×${s.quantity}`).join(', ') || 'none'}]`,
      performedBy,
      unitId: request.unitId,
    },
  });

  return slices;
}

// GET /api/requests — list requests based on role
router.get('/', authenticate, async (req, res) => {
  try {
    const { status, page, limit, fromDate, toDate } = req.query;
    const { skip, take } = paginate(page, limit);

    const where = {};
    applyDateFilter(where, { fromDate, toDate });

    // Role-based filtering — requester roles see only their own
    if (REQUESTER_ROLES.includes(req.user.role)) {
      where.managerId = req.user.id;
    }
    // STORE_MANAGER and ADMIN see all
    if (status) where.status = status;

    const [requests, total] = await Promise.all([
      prisma.productRequest.findMany({
        where,
        include: {
          manager: { select: { id: true, name: true, username: true, role: true } },
          unit: { select: { id: true, name: true, code: true } },
          items: {
            include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } },
          },
        },
        orderBy: { createdAt: 'desc' },
        skip,
        take,
      }),
      prisma.productRequest.count({ where }),
    ]);

    res.json({ requests, total, page: Math.ceil(skip / take) + 1, totalPages: Math.ceil(total / take) });
  } catch (error) {
    console.error('Get requests error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// GET /api/requests/pending-count
router.get('/pending-count', authenticate, async (req, res) => {
  try {
    const count = await prisma.productRequest.count({ where: { status: 'PENDING' } });
    res.json({ count });
  } catch (error) {
    console.error('Pending count error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// GET /api/requests/:id
router.get('/:id', authenticate, async (req, res) => {
  try {
    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: {
        manager: { select: { id: true, name: true, username: true, role: true, unit: { select: { name: true, code: true } } } },
        unit: { select: { id: true, name: true, code: true } },
        items: {
          include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true, category: true } } },
        },
      },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });

    // Requester roles can only view their own requests
    if (REQUESTER_ROLES.includes(req.user.role) && request.managerId !== req.user.id) {
      return res.status(403).json({ error: 'Access denied' });
    }

    res.json(request);
  } catch (error) {
    console.error('Get request error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// POST /api/requests — Requester creates a product request
router.post('/', authenticate, authorize(...REQUESTER_ROLES), async (req, res) => {
  try {
    const data = createRequestSchema.parse(req.body);

    if (!req.user.unitId && UNIT_BOUND_ROLES.includes(req.user.role)) {
      return res.status(400).json({ error: 'You must be assigned to a unit to create requests' });
    }

    const requestNumber = await generateSequentialNumber(prisma, 'MIV');

    const request = await prisma.productRequest.create({
      data: {
        requestNumber,
        managerId: req.user.id,
        unitId: req.user.unitId || null,
        notes: data.notes || null,
        remarks: data.remarks || null,
        // referenceNo auto-mirrors the MIV request number — no manual entry.
        referenceNo: requestNumber,
        items: {
          create: data.items.map(item => ({
            productId: item.productId,
            quantity: item.quantity,
            purpose: item.purpose || null,
          })),
        },
      },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        items: {
          include: { product: { select: { id: true, name: true, sku: true, unit: true } } },
        },
      },
    });

    // Audit log
    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'CREATE',
        entity: 'ProductRequest',
        entityId: request.id,
        details: {
          requestNumber,
          unit: req.user.unit?.code,
          itemCount: data.items.length,
        },
        ipAddress: req.ip,
      },
    });

    // Notify store managers
    await prisma.notification.create({
      data: {
        type: 'NEW_REQUEST',
        title: `New Request: ${requestNumber}`,
        message: `${req.user.name}${req.user.unit ? ` (${req.user.unit.name})` : ` (${req.user.role})`} has submitted a new product request with ${data.items.length} item(s).`,
        targetRole: 'STORE_MANAGER',
        sentById: req.user.id,
      },
    });

    res.status(201).json(request);
  } catch (error) {
    if (error instanceof z.ZodError) {
      return res.status(400).json({ error: 'Invalid input', details: error.errors });
    }
    console.error('Create request error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// PUT /api/requests/:id/approve — Store Manager accepts the MIV.
// Body: {} — store fills nothing. Everything is auto-derived:
//   • approvedQty = qtyIssued = original requested qty
//   • issueNo auto-generated, issueDate = now()
//   • materialBatchNo = FIFO-picked product batch numbers
//   • stock decremented immediately (global + per-unit), batch remaining drawn down
//   • status flips straight to COLLECTED — no separate "collect" step
router.put('/:id/approve', authenticate, authorize('STORE_MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: {
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } } },
        manager: { select: { id: true, name: true, role: true } },
        unit: { select: { id: true, name: true, code: true } },
      },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.status !== 'PENDING') {
      return res.status(400).json({ error: 'Only pending requests can be approved' });
    }

    // Partial issue: no longer all-or-nothing. Issue whatever is available to
    // the requester right now (own reserved bucket + unassigned pool), per item.
    // Items with insufficient stock get whatever's there; the remainder waits
    // and the MIV is left PARTIAL so the store can top it up once stock arrives.
    const requesterDept = request.unitId ? null : deptForRole(request.manager?.role);
    const availabilityByItem = await computeAvailability(prisma, request, requesterDept);

    // Decide how much to issue per item this round = min(requested, available).
    const takeByItem = {};
    let totalIssuedQty = 0;
    for (const ri of request.items) {
      const av = availabilityByItem[ri.id] || { available: 0 };
      const take = Math.max(0, Math.min(ri.quantity, av.available));
      takeByItem[ri.id] = take;
      totalIssuedQty += take;
    }

    // An Issue No is only minted when something actually leaves stock.
    const issueNo = totalIssuedQty > 0 ? await generateSequentialNumber(prisma, 'ISS') : null;
    const now = new Date();
    const fifoSlicesByItem = {};

    await prisma.$transaction(async (tx) => {
      for (const item of request.items) {
        const take = takeByItem[item.id] || 0;
        const slices = await issueItemQty(tx, {
          request,
          item,
          take,
          requesterDept,
          availability: availabilityByItem[item.id],
          performedBy: req.user.id,
          note: `MIV ${request.requestNumber} accepted by ${req.user.name} for ${request.unit?.name || request.manager?.name || 'requester'}`,
        });
        fifoSlicesByItem[item.id] = slices;
        const batchNoString = slices.map(s => s.batchNo).filter(Boolean).join(', ') || null;

        await tx.requestItem.update({
          where: { id: item.id },
          data: {
            approvedQty: item.quantity, // full accepted qty; qtyIssued tracks what's gone out
            qtyIssued: take,
            collectedQty: take,
            materialBatchNo: batchNoString,
          },
        });
      }

      // COLLECTED only when every item is fully issued; otherwise PARTIAL (waiting).
      const fullyIssued = request.items.every(ri => (takeByItem[ri.id] || 0) >= ri.quantity - 0.001);
      await tx.productRequest.update({
        where: { id: req.params.id },
        data: {
          status: fullyIssued ? 'COLLECTED' : 'PARTIAL',
          clearedById: req.user.id,
          clearedAt: now,
          ...(fullyIssued ? { collectedAt: now } : {}),
          ...(issueNo ? { issueNo, issueDate: now } : {}),
        },
      });
    });

    const fullyIssuedCount = request.items.filter(i => (takeByItem[i.id] || 0) >= i.quantity - 0.001).length;
    const allDone = fullyIssuedCount === request.items.length;

    const updated = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } } },
      },
    });

    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'APPROVE',
        entity: 'ProductRequest',
        entityId: request.id,
        details: {
          requestNumber: request.requestNumber,
          issueNo,
          action: allDone ? 'ACCEPTED_AND_ISSUED' : 'ACCEPTED_AND_PARTIALLY_ISSUED',
          items: request.items.map(i => ({
            product: i.product?.name,
            qty: i.quantity,
            issued: takeByItem[i.id] || 0,
            pending: Math.max(0, i.quantity - (takeByItem[i.id] || 0)),
            fifoBatches: fifoSlicesByItem[i.id] || [],
          })),
        },
        ipAddress: req.ip,
      },
    });

    await prisma.notification.create({
      data: {
        type: 'REQUEST_APPROVED',
        title: `MIV ${request.requestNumber} accepted`,
        message: allDone
          ? `Your MIV ${request.requestNumber} has been accepted by ${req.user.name}. Issue No: ${issueNo}. Materials issued from stock.`
          : `Your MIV ${request.requestNumber} has been accepted by ${req.user.name} (partial). ${fullyIssuedCount}/${request.items.length} item(s) issued${issueNo ? ` — Issue No: ${issueNo}` : ''}; the remaining items are waiting on stock and will be issued when available.`,
        targetRole: request.manager?.role || 'MANAGER',
        sentById: req.user.id,
      },
    });

    // Low-stock notifications after issue.
    for (const item of request.items) {
      const product = await prisma.product.findUnique({ where: { id: item.productId } });
      if (product && product.minStockLevel > 0 && product.currentStock <= product.minStockLevel) {
        const existing = await prisma.notification.findFirst({
          where: { productId: product.id, isRead: false, type: 'LOW_STOCK' },
        });
        if (!existing) {
          await prisma.notification.create({
            data: {
              type: 'LOW_STOCK',
              title: `LOW STOCK: ${product.name}`,
              message: `${product.name} (${product.sku}) stock is at ${product.currentStock} ${product.unit}. Minimum level: ${product.minStockLevel}.`,
              productId: product.id,
              targetRole: 'STORE_MANAGER',
            },
          });
        }
      }
    }

    res.json(updated);
  } catch (error) {
    console.error('Approve request error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
});

// PUT /api/requests/:id/issue-available — Store Manager tops up a PARTIAL MIV.
// Issues whatever is now available against each item's still-pending qty
// (pending = approvedQty − qtyIssued). Advances the MIV to COLLECTED once every
// item is fully issued, otherwise it stays PARTIAL for the next top-up.
router.put('/:id/issue-available', authenticate, authorize('STORE_MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: {
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } } },
        manager: { select: { id: true, name: true, role: true } },
        unit: { select: { id: true, name: true, code: true } },
      },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.status !== 'PARTIAL') {
      return res.status(400).json({ error: 'Only partially-issued MIVs can be topped up' });
    }

    const requesterDept = request.unitId ? null : deptForRole(request.manager?.role);
    const availabilityByItem = await computeAvailability(prisma, request, requesterDept);

    // This round's take per item = min(stillPending, availableNow).
    const takeByItem = {};
    let totalIssuedQty = 0;
    for (const ri of request.items) {
      const approved = ri.approvedQty ?? ri.quantity;
      const pending = Math.max(0, approved - (ri.qtyIssued || 0));
      const av = availabilityByItem[ri.id] || { available: 0 };
      const take = Math.max(0, Math.min(pending, av.available));
      takeByItem[ri.id] = take;
      totalIssuedQty += take;
    }

    if (totalIssuedQty <= 0) {
      return res.status(400).json({ error: 'No additional stock is available to issue for the pending items yet.' });
    }

    // Reuse the existing Issue No if one was minted at accept time; otherwise mint now.
    const issueNo = request.issueNo || await generateSequentialNumber(prisma, 'ISS');
    const now = new Date();
    const fifoSlicesByItem = {};

    await prisma.$transaction(async (tx) => {
      for (const item of request.items) {
        const take = takeByItem[item.id] || 0;
        if (take <= 0) { fifoSlicesByItem[item.id] = []; continue; }
        const slices = await issueItemQty(tx, {
          request,
          item,
          take,
          requesterDept,
          availability: availabilityByItem[item.id],
          performedBy: req.user.id,
          note: `MIV ${request.requestNumber} top-up issue by ${req.user.name} for ${request.unit?.name || request.manager?.name || 'requester'}`,
        });
        fifoSlicesByItem[item.id] = slices;
        const newBatchNo = slices.map(s => s.batchNo).filter(Boolean).join(', ');
        const mergedBatchNo = [item.materialBatchNo, newBatchNo].filter(Boolean).join(', ') || null;

        await tx.requestItem.update({
          where: { id: item.id },
          data: {
            qtyIssued: { increment: take },
            collectedQty: { increment: take },
            materialBatchNo: mergedBatchNo,
          },
        });
      }

      const fullyIssued = request.items.every(ri => {
        const approved = ri.approvedQty ?? ri.quantity;
        return ((ri.qtyIssued || 0) + (takeByItem[ri.id] || 0)) >= approved - 0.001;
      });

      await tx.productRequest.update({
        where: { id: req.params.id },
        data: {
          status: fullyIssued ? 'COLLECTED' : 'PARTIAL',
          issueNo,
          issueDate: request.issueDate || now,
          ...(fullyIssued ? { collectedAt: now } : {}),
        },
      });
    });

    const fullyIssuedCount = request.items.filter(ri => {
      const approved = ri.approvedQty ?? ri.quantity;
      return ((ri.qtyIssued || 0) + (takeByItem[ri.id] || 0)) >= approved - 0.001;
    }).length;
    const allDone = fullyIssuedCount === request.items.length;

    const updated = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } } },
      },
    });

    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'ISSUE_AVAILABLE',
        entity: 'ProductRequest',
        entityId: request.id,
        details: {
          requestNumber: request.requestNumber,
          issueNo,
          completed: allDone,
          items: request.items.map(i => ({
            product: i.product?.name,
            issuedThisRound: takeByItem[i.id] || 0,
            fifoBatches: fifoSlicesByItem[i.id] || [],
          })),
        },
        ipAddress: req.ip,
      },
    });

    await prisma.notification.create({
      data: {
        type: 'REQUEST_APPROVED',
        title: allDone ? `MIV ${request.requestNumber} fully issued` : `MIV ${request.requestNumber} partly issued`,
        message: allDone
          ? `Your MIV ${request.requestNumber} is now fully issued by ${req.user.name}. Issue No: ${issueNo}.`
          : `${req.user.name} issued more stock against your MIV ${request.requestNumber}. Some items are still waiting on stock.`,
        targetRole: request.manager?.role || 'MANAGER',
        sentById: req.user.id,
      },
    });

    // Low-stock notifications after issue.
    for (const item of request.items) {
      const product = await prisma.product.findUnique({ where: { id: item.productId } });
      if (product && product.minStockLevel > 0 && product.currentStock <= product.minStockLevel) {
        const existing = await prisma.notification.findFirst({
          where: { productId: product.id, isRead: false, type: 'LOW_STOCK' },
        });
        if (!existing) {
          await prisma.notification.create({
            data: {
              type: 'LOW_STOCK',
              title: `LOW STOCK: ${product.name}`,
              message: `${product.name} (${product.sku}) stock is at ${product.currentStock} ${product.unit}. Minimum level: ${product.minStockLevel}.`,
              productId: product.id,
              targetRole: 'STORE_MANAGER',
            },
          });
        }
      }
    }

    res.json(updated);
  } catch (error) {
    console.error('Issue-available request error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
});

// PUT /api/requests/:id/reject — Store Manager rejects
router.put('/:id/reject', authenticate, authorize('STORE_MANAGER', 'ADMIN'), async (req, res) => {
  try {
    const { clearanceNotes } = req.body;

    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: { manager: { select: { name: true } } },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.status !== 'PENDING') {
      return res.status(400).json({ error: 'Only pending requests can be rejected' });
    }

    const updated = await prisma.productRequest.update({
      where: { id: req.params.id },
      data: {
        status: 'REJECTED',
        clearanceNotes: clearanceNotes || 'Request rejected',
        clearedById: req.user.id,
        clearedAt: new Date(),
      },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true } } } },
      },
    });

    // Audit log
    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'REJECT',
        entity: 'ProductRequest',
        entityId: request.id,
        details: { requestNumber: request.requestNumber, action: 'REJECTED', reason: clearanceNotes },
        ipAddress: req.ip,
      },
    });

    // Notify the creator (look up their role)
    const creator = await prisma.user.findUnique({ where: { id: request.managerId }, select: { role: true } });
    await prisma.notification.create({
      data: {
        type: 'REQUEST_REJECTED',
        title: `Request ${request.requestNumber} Rejected`,
        message: `Your product request ${request.requestNumber} has been rejected. Reason: ${clearanceNotes || 'No reason provided'}`,
        targetRole: creator?.role || 'MANAGER',
        sentById: req.user.id,
      },
    });

    res.json(updated);
  } catch (error) {
    console.error('Reject request error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// PUT /api/requests/:id/collect — Requester collects items (full or partial)
// Body: { items?: [{ id, collectedQty }] }  — defaults to each item's remaining approvedQty
router.put('/:id/collect', authenticate, authorize(...REQUESTER_ROLES), async (req, res) => {
  try {
    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: { items: { include: { product: true } }, unit: true },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.managerId !== req.user.id) {
      return res.status(403).json({ error: 'You can only collect your own requests' });
    }
    if (request.status !== 'APPROVED' && request.status !== 'PARTIAL') {
      return res.status(400).json({ error: 'Only approved or partially collected requests can be collected' });
    }

    // The collector is the requester (checked above), so their role gives the
    // owning department for non-unit MIVs.
    const requesterDept = request.unitId ? null : deptForRole(req.user.role);

    // Build collect-plan: how much each item takes this round (delta)
    const bodyItems = Array.isArray(req.body?.items) ? req.body.items : null;
    const plan = [];
    for (const item of request.items) {
      const approved = item.approvedQty ?? item.quantity;
      const alreadyTaken = item.collectedQty || 0;
      const maxRemaining = Math.max(0, approved - alreadyTaken);

      let take;
      if (bodyItems) {
        const override = bodyItems.find((b) => b.id === item.id);
        if (!override) { take = 0; continue; } // omitted = collect 0 this round
        take = Number(override.collectedQty);
        if (!Number.isFinite(take) || take < 0) {
          return res.status(400).json({ error: `Invalid collectedQty for item ${item.id}` });
        }
      } else {
        take = maxRemaining; // default: collect everything remaining
      }

      if (take > maxRemaining) {
        return res.status(400).json({
          error: `collectedQty ${take} exceeds remaining ${maxRemaining} for ${item.product.name}`,
        });
      }
      if (take > 0) plan.push({ item, take });
    }

    if (plan.length === 0) {
      return res.status(400).json({ error: 'Nothing to collect — provide at least one item with qty > 0' });
    }

    // FIFO: deduct from oldest batches first
    const fifoIssuedByItem = {};
    await prisma.$transaction(async (tx) => {
      for (const { item, take } of plan) {
        const batches = await tx.productBatch.findMany({
          where: { productId: item.productId, remaining: { gt: 0 } },
          orderBy: { receivedDate: 'asc' },
        });

        let toFulfill = take;
        const issuedSlices = [];
        for (const batch of batches) {
          if (toFulfill <= 0) break;
          const slice = Math.min(batch.remaining, toFulfill);
          await tx.productBatch.update({
            where: { id: batch.id },
            data: { remaining: batch.remaining - slice },
          });
          issuedSlices.push({
            batchId: batch.id,
            batchNo: batch.batchNo,
            receivedDate: batch.receivedDate,
            quantity: slice,
          });
          toFulfill -= slice;
        }
        fifoIssuedByItem[item.id] = issuedSlices;

        await tx.product.update({
          where: { id: item.productId },
          data: { currentStock: { decrement: take } },
        });

        // Decrement the requester's own reserved bucket. Unit requesters draw from
        // their unit bucket; non-unit owner departments (QC, Designs, …) from their
        // department bucket. Unit-less non-owner MIVs draw the unassigned pool —
        // only Product.currentStock is decremented (done above).
        if (request.unitId) {
          const pus = await tx.productUnitStock.findUnique({
            where: { productId_unitId: { productId: item.productId, unitId: request.unitId } },
          });
          if (!pus || pus.quantity < take - 0.001) {
            throw new Error(`Unit ${request.unit?.code || request.unitId} stock for ${item.product?.name || 'product'} is insufficient — please raise an inventory transfer first.`);
          }
          await tx.productUnitStock.update({
            where: { productId_unitId: { productId: item.productId, unitId: request.unitId } },
            data: { quantity: { decrement: take } },
          });
        } else if (requesterDept) {
          const pds = await tx.productDeptStock.findUnique({
            where: { productId_dept: { productId: item.productId, dept: requesterDept } },
          });
          if (!pds || pds.quantity < take - 0.001) {
            throw new Error(`${requesterDept} department stock for ${item.product?.name || 'product'} is insufficient — please raise an inventory transfer first.`);
          }
          await tx.productDeptStock.update({
            where: { productId_dept: { productId: item.productId, dept: requesterDept } },
            data: { quantity: { decrement: take } },
          });
        }

        await tx.requestItem.update({
          where: { id: item.id },
          data: { collectedQty: { increment: take } },
        });

        const batchNote = issuedSlices.length > 0
          ? ` [FIFO: ${issuedSlices.map(s => `${s.batchNo || 'NO-BATCH'}×${s.quantity}`).join(', ')}]`
          : '';

        await tx.stockMovement.create({
          data: {
            productId: item.productId,
            type: 'OUT',
            quantity: take,
            referenceType: 'ProductRequest',
            referenceId: request.id,
            batchNumber: issuedSlices.map(s => s.batchNo).filter(Boolean).join(', ') || null,
            notes: `Collected by ${req.user.name} for ${request.unit?.name || request.manager?.name || 'requester'} (${request.requestNumber})${batchNote}`,
            performedBy: req.user.id,
            unitId: request.unitId,
          },
        });
      }

      // Determine final status: COLLECTED if every item fully taken, else PARTIAL
      const refreshed = await tx.requestItem.findMany({ where: { requestId: request.id } });
      const fullyDone = refreshed.every((ri) => (ri.collectedQty || 0) >= (ri.approvedQty ?? ri.quantity));

      await tx.productRequest.update({
        where: { id: req.params.id },
        data: fullyDone
          ? { status: 'COLLECTED', collectedAt: new Date() }
          : { status: 'PARTIAL' },
      });
    });

    // Audit log
    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'COLLECT',
        entity: 'ProductRequest',
        entityId: request.id,
        details: {
          requestNumber: request.requestNumber,
          unit: request.unit?.code || null,
          items: plan.map(({ item, take }) => ({
            product: item.product.name,
            qtyTaken: take,
            fifoBatches: fifoIssuedByItem[item.id] || [],
          })),
        },
        ipAddress: req.ip,
      },
    });

    // Check for low stock and auto-notify
    for (const item of request.items) {
      const product = await prisma.product.findUnique({ where: { id: item.productId } });
      if (product && product.minStockLevel > 0 && product.currentStock <= product.minStockLevel) {
        const existing = await prisma.notification.findFirst({
          where: { productId: product.id, isRead: false, type: 'LOW_STOCK' },
        });
        if (!existing) {
          await prisma.notification.create({
            data: {
              type: 'LOW_STOCK',
              title: `LOW STOCK: ${product.name}`,
              message: `${product.name} (${product.sku}) stock is at ${product.currentStock} ${product.unit}. Minimum level: ${product.minStockLevel}.`,
              productId: product.id,
              targetRole: 'STORE_MANAGER',
            },
          });
        }
      }
    }

    const updated = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } } },
      },
    });

    res.json(updated);
  } catch (error) {
    console.error('Collect request error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// PUT /api/requests/:id/kill-remaining — Requester closes a PARTIAL request without collecting more
router.put('/:id/kill-remaining', authenticate, authorize(...REQUESTER_ROLES), async (req, res) => {
  try {
    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
      include: { items: { include: { product: true } }, unit: true },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.managerId !== req.user.id) {
      return res.status(403).json({ error: 'You can only modify your own requests' });
    }
    if (request.status !== 'PARTIAL') {
      return res.status(400).json({ error: 'Only partially collected requests can be closed this way' });
    }

    const updated = await prisma.productRequest.update({
      where: { id: req.params.id },
      data: { status: 'COLLECTED', collectedAt: new Date() },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true, currentStock: true } } } },
      },
    });

    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'KILL_REMAINING',
        entity: 'ProductRequest',
        entityId: request.id,
        details: {
          requestNumber: request.requestNumber,
          items: request.items.map((i) => ({
            product: i.product.name,
            approvedQty: i.approvedQty ?? i.quantity,
            collectedQty: i.collectedQty || 0,
            killedQty: Math.max(0, (i.approvedQty ?? i.quantity) - (i.collectedQty || 0)),
          })),
        },
        ipAddress: req.ip,
      },
    });

    res.json(updated);
  } catch (error) {
    console.error('Kill remaining error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// PUT /api/requests/:id/cancel — Requester cancels own pending request
router.put('/:id/cancel', authenticate, authorize(...REQUESTER_ROLES), async (req, res) => {
  try {
    const request = await prisma.productRequest.findUnique({
      where: { id: req.params.id },
    });

    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.managerId !== req.user.id) {
      return res.status(403).json({ error: 'You can only cancel your own requests' });
    }
    if (request.status !== 'PENDING') {
      return res.status(400).json({ error: 'Only pending requests can be cancelled' });
    }

    const updated = await prisma.productRequest.update({
      where: { id: req.params.id },
      data: { status: 'CANCELLED' },
      include: {
        manager: { select: { id: true, name: true } },
        unit: { select: { id: true, name: true, code: true } },
        items: { include: { product: { select: { id: true, name: true, sku: true, unit: true } } } },
      },
    });

    await prisma.auditLog.create({
      data: {
        userId: req.user.id,
        action: 'CANCEL',
        entity: 'ProductRequest',
        entityId: request.id,
        details: { requestNumber: request.requestNumber, action: 'CANCELLED' },
        ipAddress: req.ip,
      },
    });

    res.json(updated);
  } catch (error) {
    console.error('Cancel request error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

module.exports = router;
