-- Rename TENDER_MANAGER → SUPPLY_CHAIN, rename misspelled METEOROLOGY → METROLOGY,
-- add new roles DESIGNS / FINANCE / PLANNING / LOGISTICS.
-- ALTER TYPE ... RENAME VALUE preserves existing user.role values.

ALTER TYPE "Role" RENAME VALUE 'TENDER_MANAGER' TO 'SUPPLY_CHAIN';
ALTER TYPE "Role" RENAME VALUE 'METEOROLOGY' TO 'METROLOGY';

ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'DESIGNS';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FINANCE';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'PLANNING';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'LOGISTICS';
