import { formatDate } from './shared';

const escapeHtml = (s = '') =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const formatINR = (n) => {
  const num = Number(n || 0);
  const rupees = Math.floor(num);
  const paise = Math.round((num - rupees) * 100);
  return `${rupees.toLocaleString('en-IN')}-${String(paise).padStart(2, '0')}`;
};

export function buildPOWordHtml(order) {
  const items = order?.items || [];
  const pr = order?.purchaseRequest;
  const quotation = order?.quotation;

  const supplierAddress = quotation?.supplierAddress || '';
  const supplierContact = quotation?.supplierContact || '';
  const addressLines = supplierAddress
    ? supplierAddress.split(/\r?\n|,\s*/).map(x => x.trim()).filter(Boolean)
    : [];

  const subjectMaterials = items.slice(0, 3).map(i => i.productName).filter(Boolean).join(', ');
  const subjectMore = items.length > 3 ? `, +${items.length - 3} more` : '';
  const subject = order?.customName
    ? `Purchase Order for Supply of ${order.customName}`
    : `Purchase Order for Supply of ${subjectMaterials}${subjectMore}`;

  const itemsRows = items.map((it, idx) => `
    <tr>
      <td class='center'>${idx + 1}</td>
      <td>${escapeHtml(it.productName || '')}</td>
      <td class='center'>${escapeHtml(`${it.quantity} ${it.productUnit || ''}`)}</td>
      <td class='right'>${formatINR(it.unitPrice)}</td>
      <td class='right'>${formatINR(it.totalPrice)}</td>
    </tr>
  `).join('');

  return `
    <div class='header-row'>
      <div>
        <h2>Ramesh's Aerospace Products &amp; Services Pvt. Ltd.</h2>
      </div>
      <div class='stamp'>
        <div>Form no.: RAPS/PO Rev 01</div>
        <div>Dt: 05/06/2024</div>
      </div>
    </div>
    <hr/>

    <table style='border:0; margin-bottom:8pt;'>
      <tr style='border:0;'>
        <td style='border:0; font-weight:bold;'>Ref: ${escapeHtml(order?.orderNumber || '—')}</td>
        <td style='border:0; font-weight:bold; text-align:right;'>Date: ${escapeHtml(formatDate(order?.createdAt))}</td>
      </tr>
      <tr style='border:0;'>
        <td style='border:0; font-weight:bold;' colspan='2'>PR No: ${escapeHtml(pr?.requestNumber || '—')} &nbsp; Dt: ${escapeHtml(formatDate(pr?.createdAt))}</td>
      </tr>
    </table>

    <p>To,<br/>
    <b>M/s ${escapeHtml(order?.supplierName || quotation?.supplierName || '—')}</b><br/>
    ${addressLines.map(l => escapeHtml(l)).join('<br/>')}
    ${supplierContact ? `<br/>Kind Attn: ${escapeHtml(supplierContact)}` : ''}
    </p>

    <p>Dear Sir,</p>
    <p><b>Subject: ${escapeHtml(subject)}.</b></p>
    ${quotation?.quotationNumber ? `<p>Ref: Your Quotation No: ${escapeHtml(quotation.quotationNumber)} Dt: ${escapeHtml(formatDate(quotation.createdAt))}</p>` : ''}

    <p>With reference to the above and subsequent discussions, we are pleased to place an order on you for the supply of the following.</p>

    <table>
      <thead>
        <tr>
          <th style='width:7%;'>Sl. No.</th>
          <th style='width:49%;'>Material Description and Specification</th>
          <th style='width:14%;'>Qty</th>
          <th style='width:15%;'>Rate</th>
          <th style='width:15%;'>Amount</th>
        </tr>
      </thead>
      <tbody>
        ${itemsRows}
        <tr class='totalRow'>
          <td colspan='4' class='right'><b>Total</b></td>
          <td class='right'><b>${formatINR(order?.totalAmount)}</b></td>
        </tr>
      </tbody>
    </table>

    <p><i>Note: Test reports / inspection certificates shall be provided along with the invoice at the time of delivery.</i></p>

    <p><b>Terms &amp; Conditions:</b></p>
    <p>
      GST: Extra @18% or as applicable.<br/>
      Payment: Mutually agreeable terms.<br/>
      Delivery: As mutually agreed from the date of PO.<br/>
      Packing: Standard packing to avoid transit damage.<br/>
      Inspection: As per RAPS QA / Customer QA standard.<br/>
      Please mention our PO number in the invoice copy.<br/>
      For all other terms and conditions refer annexure attached.<br/>
      Jurisdiction: Any disputes shall be subject to the jurisdiction of Vijayawada.
    </p>

    <p>Thanking you,<br/>
    Yours sincerely,<br/>
    For Ramesh's Aerospace Products &amp; Services Pvt. Ltd.,</p>

    <p style='margin-top:36pt;'>(${escapeHtml(order?.createdBy?.name || 'Authorised Signatory')})</p>

    <hr/>
    <p class='muted center'>Generated by RAPS ERP · PO ${escapeHtml(order?.orderNumber || '')}</p>
  `;
}
